### ISSUE TITLE
Unable to install with cakephp 3.0.1

### ISSUE THREAD

**Issue by rochamarcelo** [gourmet/validation#1]
Composer output:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: cakephp/cakephp[3.0.x-dev, 3.0.1].
    - Can only install one of: cakephp/cakephp[3.0.x-dev, 3.0.1].
    - gourmet/validation v1.0.0 requires cakephp/cakephp 3.0.*-dev -> satisfiable by cakephp/cakephp[3.0.x-dev].
    - Installation request for gourmet/validation ~1.0 -> satisfiable by gourmet/validation[v1.0.0].
    - Installation request for cakephp/cakephp == 3.0.1.0 -> satisfiable by cakephp/cakephp[3.0.1].

**Comment by jadb** [comment]
Thanks for reporting it!
